export const requiredTables = [
  "users",
  "profiles",
  "auth_sessions",
  "organizations",
  "organization_billing",
  "memberships",
  "customers",
  "leads",
  "jobs",
  "quotes",
  "quote_line_items",
  "invoices",
  "invoice_line_items",
  "invoice_payments",
  "services",
  "technicians",
  "job_notes",
  "job_status_events",
  "inspections",
  "inspection_items",
  "inspection_photos",
  "inspection_required_fields",
  "pricebook_items",
  "pricebook_bundles",
  "pricebook_bundle_items",
  "inventory_items",
  "inventory_locations",
  "inventory_movements",
  "organization_settings",
  "portal_magic_links",
  "portal_sessions",
  "portal_access_events",
  "automation_templates",
  "automation_rules",
  "automation_runs",
  "automation_logs",
  "automation_pending_actions",
  "automation_scheduled_runs",
  "automation_settings",
  "crm_tasks",
  "recent_calls",
  "owned_phone_numbers",
  "txt_conversations",
  "txt_messages",
  "sms_templates",
  "call_flow_configs",
  "call_flow_business_hours",
  "call_flow_ivr_options",
  "callback_tasks",
  "missed_call_sms_settings",
  "missed_call_sms_cooldowns",
  "recent_call_sms_logs",
  "recent_call_activity_events",
] as const;

export const requiredColumns = [
  { table: "memberships", columns: ["user_id", "organization_id", "role", "status"] },
  { table: "organization_billing", columns: ["organization_id", "plan_key", "billing_status"] },
  { table: "auth_sessions", columns: ["user_id", "active_organization_id", "session_token_hash"] },
  { table: "customers", columns: ["organization_id", "full_name", "phone"] },
  { table: "jobs", columns: ["organization_id", "customer_id", "status"] },
  { table: "quotes", columns: ["organization_id", "job_id", "status"] },
  { table: "invoices", columns: ["organization_id", "job_id", "status"] },
  { table: "invoice_payments", columns: ["organization_id", "invoice_id"] },
  { table: "services", columns: ["organization_id", "service_type"] },
  { table: "technicians", columns: ["organization_id", "display_name"] },
  { table: "job_notes", columns: ["organization_id", "job_id"] },
  { table: "job_status_events", columns: ["organization_id", "job_id"] },
  { table: "inspections", columns: ["organization_id", "customer_id", "job_id"] },
  { table: "inspection_items", columns: ["organization_id", "inspection_id", "item_key"] },
  { table: "inspection_photos", columns: ["organization_id", "inspection_id"] },
  { table: "inspection_required_fields", columns: ["organization_id", "inspection_id", "field_key"] },
  { table: "pricebook_items", columns: ["organization_id", "internal_sku"] },
  { table: "pricebook_bundles", columns: ["organization_id", "name"] },
  { table: "pricebook_bundle_items", columns: ["organization_id", "bundle_id", "pricebook_item_id"] },
  { table: "inventory_items", columns: ["organization_id", "internal_sku"] },
  { table: "inventory_locations", columns: ["organization_id", "name"] },
  { table: "inventory_movements", columns: ["organization_id", "inventory_item_id"] },
  { table: "organization_settings", columns: ["settings_key", "organization_id"] },
  { table: "portal_magic_links", columns: ["organization_id", "customer_id", "token_hash"] },
  { table: "portal_sessions", columns: ["organization_id", "customer_id", "session_token_hash"] },
  { table: "portal_access_events", columns: ["organization_id", "customer_id", "event_type"] },
  { table: "recent_calls", columns: ["provider", "provider_event_id", "call_status", "processing_status"] },
  { table: "owned_phone_numbers", columns: ["phone_number_normalized", "provider", "is_active"] },
  { table: "txt_conversations", columns: ["public_conversation_code", "owned_phone_number_id", "customer_phone_number_normalized"] },
  { table: "txt_messages", columns: ["conversation_id", "provider_message_id", "status"] },
  { table: "sms_templates", columns: ["name", "is_active", "sort_order", "quick_pick_order"] },
  { table: "call_flow_configs", columns: ["config_name", "is_active", "time_zone"] },
  { table: "call_flow_business_hours", columns: ["call_flow_config_id", "day_key", "sort_order"] },
  { table: "call_flow_ivr_options", columns: ["call_flow_config_id", "digit", "sort_order"] },
  { table: "callback_tasks", columns: ["recent_call_id", "status", "due_at"] },
  { table: "missed_call_sms_settings", columns: ["settings_key", "is_enabled", "cooldown_seconds"] },
  { table: "missed_call_sms_cooldowns", columns: ["phone_number_normalized", "next_allowed_at"] },
  { table: "recent_call_sms_logs", columns: ["recent_call_id", "customer_id", "read_at"] },
  { table: "recent_call_activity_events", columns: ["recent_call_id", "event_key"] },
] as const;

export const requiredIndexes = [
  { table: "memberships", columns: ["user_id", "organization_id"], isUnique: true },
  { table: "auth_sessions", columns: ["session_token_hash"], isUnique: true },
  { table: "pricebook_items", columns: ["organization_id", "internal_sku"], isUnique: true },
  { table: "inventory_items", columns: ["organization_id", "internal_sku"], isUnique: true },
  { table: "inventory_locations", columns: ["organization_id", "name"], isUnique: true },
  { table: "recent_calls", columns: ["provider", "provider_event_id"], isUnique: true },
  { table: "recent_calls", columns: ["created_at"], isUnique: false },
  { table: "owned_phone_numbers", columns: ["provider", "provider_number_id"], isUnique: false },
  { table: "txt_conversations", columns: ["owned_phone_number_normalized", "customer_phone_number_normalized", "is_archived"], isUnique: true },
  { table: "txt_messages", columns: ["conversation_id", "created_at"], isUnique: false },
  { table: "sms_templates", columns: ["is_active", "sort_order", "created_at"], isUnique: false },
  { table: "call_flow_business_hours", columns: ["call_flow_config_id", "day_key"], isUnique: true },
  { table: "call_flow_ivr_options", columns: ["call_flow_config_id", "digit"], isUnique: true },
  { table: "callback_tasks", columns: ["recent_call_id"], isUnique: false },
  { table: "recent_call_sms_logs", columns: ["recent_call_id"], isUnique: false },
] as const;

export const requiredForeignKeys = [
  { table: "memberships", column: "user_id", referencedTable: "users", referencedColumn: "id" },
  { table: "memberships", column: "organization_id", referencedTable: "organizations", referencedColumn: "id" },
  { table: "organization_billing", column: "organization_id", referencedTable: "organizations", referencedColumn: "id" },
  { table: "auth_sessions", column: "user_id", referencedTable: "users", referencedColumn: "id" },
  { table: "auth_sessions", column: "active_organization_id", referencedTable: "organizations", referencedColumn: "id" },
  { table: "customers", column: "organization_id", referencedTable: "organizations", referencedColumn: "id" },
  { table: "jobs", column: "customer_id", referencedTable: "customers", referencedColumn: "id" },
  { table: "jobs", column: "organization_id", referencedTable: "organizations", referencedColumn: "id" },
  { table: "quotes", column: "job_id", referencedTable: "jobs", referencedColumn: "id" },
  { table: "invoices", column: "job_id", referencedTable: "jobs", referencedColumn: "id" },
  { table: "invoice_payments", column: "invoice_id", referencedTable: "invoices", referencedColumn: "id" },
  { table: "portal_magic_links", column: "customer_id", referencedTable: "customers", referencedColumn: "id" },
  { table: "portal_sessions", column: "customer_id", referencedTable: "customers", referencedColumn: "id" },
  { table: "quote_line_items", column: "quote_id", referencedTable: "quotes", referencedColumn: "id" },
  { table: "invoice_line_items", column: "invoice_id", referencedTable: "invoices", referencedColumn: "id" },
] as const;
