export const requiredTables = [
  "users",
  "billing_accounts",
  "billing_account_subscription_items",
  "customer_output_translation_records",
  "profiles",
  "auth_sessions",
  "organizations",
  "organization_billing",
  "organization_enabled_languages",
  "organization_language_entitlements",
  "memberships",
  "customers",
  "leads",
  "jobs",
  "quotes",
  "quote_line_items",
  "invoices",
  "invoice_line_items",
  "invoice_payments",
  "services",
  "technicians",
  "translation_usage_ledger",
  "job_notes",
  "job_status_events",
  "inspections",
  "ai_recommendation_runs",
  "inspection_items",
  "inspection_photos",
  "inspection_required_fields",
  "pricebook_items",
  "pricebook_bundles",
  "pricebook_bundle_items",
  "inventory_items",
  "inventory_locations",
  "inventory_movements",
  "organization_settings",
  "user_organization_language_preferences",
  "portal_magic_links",
  "portal_sessions",
  "portal_access_events",
  "automation_templates",
  "automation_rules",
  "automation_runs",
  "automation_logs",
  "automation_pending_actions",
  "automation_scheduled_runs",
  "automation_settings",
  "crm_tasks",
  "recent_calls",
  "owned_phone_numbers",
  "txt_conversations",
  "txt_messages",
  "voice_flows",
  "sms_templates",
  "call_flow_configs",
  "call_flow_business_hours",
  "call_flow_ivr_options",
  "callback_tasks",
  "missed_call_sms_settings",
  "missed_call_sms_cooldowns",
  "recent_call_sms_logs",
  "recent_call_activity_events",
  "telnyx_webhook_event_receipts",
  "marketing_profiles",
  "marketing_connected_channels",
  "marketing_campaigns",
  "marketing_campaign_items",
  "marketing_automation_rules",
  "marketing_automation_runs",
  "marketing_opportunities",
  "marketing_content_drafts",
  "marketing_content_variants",
  "marketing_oauth_states",
  "marketing_publish_jobs",
  "marketing_publish_attempts",
] as const;

export const requiredColumns = [
  {
    table: "voice_flows",
    columns: ["id", "flow_id", "telnyx_assistant_id", "title", "is_active", "created_at", "updated_at"],
  },
  {
    table: "billing_accounts",
    columns: [
      "id",
      "owner_user_id",
      "anchor_organization_id",
      "plan_key",
      "billing_status",
      "organization_limit",
      "billing_provider",
      "provider_customer_id",
      "provider_subscription_id",
      "provider_price_id",
      "last_provider_sync_at",
    ],
  },
  {
    table: "billing_account_subscription_items",
    columns: [
      "billing_account_id",
      "provider",
      "provider_subscription_item_id",
      "provider_price_id",
      "item_kind",
      "allocated_organization_id",
      "quantity",
      "is_active",
    ],
  },
  {
    table: "customer_output_translation_records",
    columns: [
      "organization_id",
      "created_by_user_id",
      "surface_key",
      "source_language_code",
      "target_language_code",
      "document_kind",
      "document_id",
      "document_line_key",
      "field_key",
      "translated_text",
      "final_text",
      "units_consumed",
      "status",
    ],
  },
  { table: "memberships", columns: ["user_id", "organization_id", "role", "status"] },
  { table: "organization_billing", columns: ["organization_id", "billing_account_id", "plan_key", "billing_status"] },
  {
    table: "organization_enabled_languages",
    columns: ["organization_id", "language_code", "activated_by_user_id", "deactivated_at"],
  },
  {
    table: "organization_language_entitlements",
    columns: [
      "organization_id",
      "billing_account_id",
      "source_plan_key",
      "billing_status",
      "language_store_enabled",
      "total_additional_language_slots",
      "total_translation_units",
    ],
  },
  { table: "auth_sessions", columns: ["user_id", "active_organization_id", "session_token_hash"] },
  {
    table: "ai_recommendation_runs",
    columns: [
      "id",
      "organization_id",
      "actor_profile_id",
      "source_channel",
      "feature_key",
      "tool_trace_json",
      "model_id",
      "prompt_version",
      "status",
      "error_code",
      "created_at",
    ],
  },
  { table: "customers", columns: ["organization_id", "full_name", "phone"] },
  { table: "jobs", columns: ["organization_id", "customer_id", "status"] },
  { table: "quotes", columns: ["organization_id", "job_id", "status"] },
  { table: "quote_line_items", columns: ["quote_id", "document_line_key", "pricebook_item_id", "sort_order"] },
  { table: "invoices", columns: ["organization_id", "job_id", "status"] },
  { table: "invoice_line_items", columns: ["invoice_id", "document_line_key", "pricebook_item_id", "sort_order"] },
  { table: "invoice_payments", columns: ["organization_id", "invoice_id"] },
  { table: "services", columns: ["organization_id", "service_type"] },
  { table: "technicians", columns: ["organization_id", "display_name"] },
  {
    table: "translation_usage_ledger",
    columns: [
      "organization_id",
      "translation_record_id",
      "created_by_user_id",
      "usage_kind",
      "source_character_count",
      "units_consumed",
    ],
  },
  { table: "job_notes", columns: ["organization_id", "job_id"] },
  { table: "job_status_events", columns: ["organization_id", "job_id"] },
  { table: "inspections", columns: ["organization_id", "customer_id", "job_id"] },
  { table: "inspection_items", columns: ["organization_id", "inspection_id", "item_key"] },
  { table: "inspection_photos", columns: ["organization_id", "inspection_id"] },
  { table: "inspection_required_fields", columns: ["organization_id", "inspection_id", "field_key"] },
  { table: "pricebook_items", columns: ["organization_id", "internal_sku"] },
  { table: "pricebook_bundles", columns: ["organization_id", "name"] },
  { table: "pricebook_bundle_items", columns: ["organization_id", "bundle_id", "pricebook_item_id"] },
  { table: "inventory_items", columns: ["organization_id", "internal_sku"] },
  { table: "inventory_locations", columns: ["organization_id", "name"] },
  { table: "inventory_movements", columns: ["organization_id", "inventory_item_id"] },
  { table: "organization_settings", columns: ["settings_key", "organization_id"] },
  { table: "user_organization_language_preferences", columns: ["user_id", "organization_id", "language_code"] },
  { table: "portal_magic_links", columns: ["organization_id", "customer_id", "token_hash"] },
  { table: "portal_sessions", columns: ["organization_id", "customer_id", "session_token_hash"] },
  { table: "portal_access_events", columns: ["organization_id", "customer_id", "event_type"] },
  { table: "recent_calls", columns: ["provider", "provider_event_id", "call_status", "processing_status"] },
  { table: "owned_phone_numbers", columns: ["phone_number_normalized", "provider", "is_active"] },
  { table: "txt_conversations", columns: ["public_conversation_code", "owned_phone_number_id", "customer_phone_number_normalized"] },
  { table: "txt_messages", columns: ["conversation_id", "provider_message_id", "status"] },
  { table: "sms_templates", columns: ["name", "is_active", "sort_order", "quick_pick_order"] },
  { table: "call_flow_configs", columns: ["config_name", "is_active", "time_zone"] },
  { table: "call_flow_business_hours", columns: ["call_flow_config_id", "day_key", "sort_order"] },
  { table: "call_flow_ivr_options", columns: ["call_flow_config_id", "digit", "sort_order"] },
  { table: "callback_tasks", columns: ["recent_call_id", "status", "due_at"] },
  { table: "missed_call_sms_settings", columns: ["settings_key", "is_enabled", "cooldown_seconds"] },
  { table: "missed_call_sms_cooldowns", columns: ["phone_number_normalized", "next_allowed_at"] },
  { table: "recent_call_sms_logs", columns: ["recent_call_id", "customer_id", "read_at"] },
  { table: "recent_call_activity_events", columns: ["recent_call_id", "event_key"] },
  { table: "telnyx_webhook_event_receipts", columns: ["provider", "provider_event_id"], isUnique: true },
  {
    table: "marketing_profiles",
    columns: [
      "id",
      "organization_id",
      "identity_json",
      "brand_voice_json",
      "publishing_preferences_json",
      "safety_preferences_json",
      "created_at",
      "updated_at",
    ],
  },
  {
    table: "marketing_connected_channels",
    columns: [
      "id",
      "organization_id",
      "channel_key",
      "channel_label",
      "connection_status",
      "account_label",
      "authorization_health",
      "permissions_status",
      "last_published_at",
      "last_failure_at",
      "metadata_json",
      "google_account_resource",
      "google_location_resource",
      "facebook_page_id",
      "encrypted_credentials",
      "pending_targets_encrypted",
      "token_expires_at",
      "created_at",
      "updated_at",
    ],
  },
  {
    table: "marketing_campaigns",
    columns: [
      "id",
      "organization_id",
      "created_by_user_id",
      "updated_by_user_id",
      "campaign_kind",
      "title",
      "objective_summary",
      "primary_service_topic",
      "geo_label",
      "geo_normalized",
      "channel_intent_json",
      "window_starts_at",
      "window_ends_at",
      "status",
      "plan_snapshot_json",
      "created_at",
      "updated_at",
    ],
  },
  {
    table: "marketing_campaign_items",
    columns: [
      "id",
      "organization_id",
      "campaign_id",
      "sort_order",
      "slot_key",
      "label",
      "plan_notes",
      "suggested_scheduled_at",
      "intended_platform_keys_json",
      "draft_id",
      "created_at",
      "updated_at",
    ],
  },
  {
    table: "marketing_automation_rules",
    columns: [
      "id",
      "organization_id",
      "name",
      "description",
      "enabled",
      "trigger_opportunity_types_json",
      "action_type",
      "action_config_json",
      "cooldown_seconds",
      "created_by_user_id",
      "updated_by_user_id",
      "created_at",
      "updated_at",
    ],
  },
  {
    table: "marketing_automation_runs",
    columns: [
      "id",
      "organization_id",
      "rule_id",
      "idempotency_key",
      "marketing_opportunity_id",
      "marketing_content_draft_id",
      "outcome",
      "skip_reason",
      "error_detail",
      "trigger_snapshot_json",
      "created_at",
    ],
  },
  {
    table: "marketing_opportunities",
    columns: [
      "id",
      "organization_id",
      "opportunity_type",
      "dedupe_key",
      "signal_version",
      "status",
      "title",
      "summary",
      "source",
      "source_entity_type",
      "source_entity_id",
      "payload_json",
      "occurred_at",
      "converted_draft_id",
      "dismissed_at",
      "dismissed_by_user_id",
      "archived_at",
      "last_refreshed_at",
      "created_at",
      "updated_at",
    ],
  },
  {
    table: "marketing_content_drafts",
    columns: [
      "id",
      "organization_id",
      "created_by_user_id",
      "updated_by_user_id",
      "title",
      "intent",
      "notes",
      "workflow_state",
      "scheduled_at",
      "created_at",
      "updated_at",
    ],
  },
  {
    table: "marketing_content_variants",
    columns: ["id", "organization_id", "draft_id", "platform_key", "body_json", "created_at", "updated_at"],
  },
  {
    table: "marketing_oauth_states",
    columns: ["id", "organization_id", "provider", "state_token", "expires_at", "consumed_at", "created_at"],
  },
  {
    table: "marketing_publish_jobs",
    columns: [
      "id",
      "organization_id",
      "draft_id",
      "status",
      "scheduled_at",
      "lease_owner",
      "leased_until",
      "publish_intent",
      "created_by_user_id",
      "created_at",
      "updated_at",
    ],
  },
  {
    table: "marketing_publish_attempts",
    columns: [
      "id",
      "organization_id",
      "publish_job_id",
      "platform_key",
      "attempt_no",
      "status",
      "outcome_code",
      "provider_http_status",
      "provider_error_json",
      "external_post_id",
      "started_at",
      "finished_at",
    ],
  },
] as const;

export const requiredIndexes = [
  {
    table: "organization_enabled_languages",
    columns: ["organization_id", "language_code"],
    isUnique: true,
  },
  {
    table: "customer_output_translation_records",
    columns: ["organization_id", "status"],
    isUnique: false,
  },
  {
    table: "customer_output_translation_records",
    columns: ["organization_id", "created_at"],
    isUnique: false,
  },
  {
    table: "customer_output_translation_records",
    columns: ["organization_id", "document_kind", "document_id"],
    isUnique: false,
  },
  {
    table: "billing_account_subscription_items",
    columns: ["provider", "provider_subscription_item_id"],
    isUnique: true,
  },
  {
    table: "billing_account_subscription_items",
    columns: ["billing_account_id"],
    isUnique: false,
  },
  {
    table: "organization_language_entitlements",
    columns: ["billing_account_id"],
    isUnique: false,
  },
  {
    table: "user_organization_language_preferences",
    columns: ["user_id", "organization_id"],
    isUnique: true,
  },
  {
    table: "translation_usage_ledger",
    columns: ["translation_record_id"],
    isUnique: true,
  },
  {
    table: "translation_usage_ledger",
    columns: ["organization_id", "created_at"],
    isUnique: false,
  },
  { table: "memberships", columns: ["user_id", "organization_id"], isUnique: true },
  { table: "auth_sessions", columns: ["session_token_hash"], isUnique: true },
  { table: "ai_recommendation_runs", columns: ["organization_id", "created_at"], isUnique: false },
  { table: "quote_line_items", columns: ["quote_id", "document_line_key"], isUnique: true },
  { table: "invoice_line_items", columns: ["invoice_id", "document_line_key"], isUnique: true },
  { table: "pricebook_items", columns: ["organization_id", "internal_sku"], isUnique: true },
  { table: "inventory_items", columns: ["organization_id", "internal_sku"], isUnique: true },
  { table: "inventory_locations", columns: ["organization_id", "name"], isUnique: true },
  { table: "recent_calls", columns: ["provider", "provider_event_id"], isUnique: true },
  { table: "voice_flows", columns: ["flow_id"], isUnique: true },
  { table: "recent_calls", columns: ["created_at"], isUnique: false },
  { table: "owned_phone_numbers", columns: ["provider", "provider_number_id"], isUnique: false },
  { table: "owned_phone_numbers", columns: ["voice_flow_id"], isUnique: false },
  { table: "txt_conversations", columns: ["owned_phone_number_normalized", "customer_phone_number_normalized", "is_archived"], isUnique: true },
  { table: "txt_messages", columns: ["conversation_id", "created_at"], isUnique: false },
  { table: "sms_templates", columns: ["is_active", "sort_order", "created_at"], isUnique: false },
  { table: "call_flow_business_hours", columns: ["call_flow_config_id", "day_key"], isUnique: true },
  { table: "call_flow_ivr_options", columns: ["call_flow_config_id", "digit"], isUnique: true },
  { table: "callback_tasks", columns: ["recent_call_id"], isUnique: false },
  { table: "recent_call_sms_logs", columns: ["recent_call_id"], isUnique: false },
  { table: "marketing_profiles", columns: ["organization_id"], isUnique: true },
  { table: "marketing_connected_channels", columns: ["organization_id"], isUnique: false },
  { table: "marketing_connected_channels", columns: ["organization_id", "channel_key"], isUnique: true },
  { table: "marketing_campaigns", columns: ["organization_id", "status"], isUnique: false },
  { table: "marketing_campaigns", columns: ["organization_id", "updated_at"], isUnique: false },
  { table: "marketing_campaign_items", columns: ["organization_id", "draft_id"], isUnique: true },
  { table: "marketing_campaign_items", columns: ["campaign_id", "sort_order"], isUnique: false },
  { table: "marketing_campaign_items", columns: ["organization_id"], isUnique: false },
  { table: "marketing_automation_rules", columns: ["organization_id", "enabled"], isUnique: false },
  { table: "marketing_automation_rules", columns: ["organization_id", "updated_at"], isUnique: false },
  {
    table: "marketing_automation_runs",
    columns: ["organization_id", "idempotency_key"],
    isUnique: true,
  },
  { table: "marketing_automation_runs", columns: ["organization_id", "rule_id", "created_at"], isUnique: false },
  { table: "marketing_automation_runs", columns: ["organization_id", "created_at"], isUnique: false },
  { table: "marketing_opportunities", columns: ["organization_id"], isUnique: false },
  { table: "marketing_opportunities", columns: ["organization_id", "dedupe_key"], isUnique: true },
  { table: "marketing_opportunities", columns: ["organization_id", "status"], isUnique: false },
  { table: "marketing_content_drafts", columns: ["organization_id", "workflow_state"], isUnique: false },
  { table: "marketing_content_drafts", columns: ["organization_id", "scheduled_at"], isUnique: false },
  { table: "marketing_content_variants", columns: ["draft_id", "platform_key"], isUnique: true },
  { table: "marketing_content_variants", columns: ["organization_id"], isUnique: false },
  { table: "marketing_oauth_states", columns: ["organization_id"], isUnique: false },
  { table: "marketing_oauth_states", columns: ["state_token"], isUnique: true },
  { table: "marketing_publish_jobs", columns: ["organization_id", "draft_id"], isUnique: false },
  { table: "marketing_publish_jobs", columns: ["status", "scheduled_at"], isUnique: false },
  { table: "marketing_publish_attempts", columns: ["publish_job_id"], isUnique: false },
  { table: "marketing_publish_attempts", columns: ["organization_id"], isUnique: false },
] as const;

export const requiredForeignKeys = [
  { table: "billing_accounts", column: "owner_user_id", referencedTable: "users", referencedColumn: "id" },
  { table: "billing_accounts", column: "anchor_organization_id", referencedTable: "organizations", referencedColumn: "id" },
  {
    table: "billing_account_subscription_items",
    column: "billing_account_id",
    referencedTable: "billing_accounts",
    referencedColumn: "id",
  },
  {
    table: "billing_account_subscription_items",
    column: "allocated_organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  { table: "memberships", column: "user_id", referencedTable: "users", referencedColumn: "id" },
  { table: "memberships", column: "organization_id", referencedTable: "organizations", referencedColumn: "id" },
  { table: "organization_billing", column: "organization_id", referencedTable: "organizations", referencedColumn: "id" },
  { table: "organization_billing", column: "billing_account_id", referencedTable: "billing_accounts", referencedColumn: "id" },
  {
    table: "organization_enabled_languages",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "organization_enabled_languages",
    column: "activated_by_user_id",
    referencedTable: "users",
    referencedColumn: "id",
  },
  {
    table: "organization_language_entitlements",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "customer_output_translation_records",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "customer_output_translation_records",
    column: "created_by_user_id",
    referencedTable: "users",
    referencedColumn: "id",
  },
  {
    table: "customer_output_translation_records",
    column: "finalized_by_user_id",
    referencedTable: "users",
    referencedColumn: "id",
  },
  {
    table: "organization_language_entitlements",
    column: "billing_account_id",
    referencedTable: "billing_accounts",
    referencedColumn: "id",
  },
  {
    table: "user_organization_language_preferences",
    column: "user_id",
    referencedTable: "users",
    referencedColumn: "id",
  },
  {
    table: "user_organization_language_preferences",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "translation_usage_ledger",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "translation_usage_ledger",
    column: "translation_record_id",
    referencedTable: "customer_output_translation_records",
    referencedColumn: "id",
  },
  {
    table: "translation_usage_ledger",
    column: "created_by_user_id",
    referencedTable: "users",
    referencedColumn: "id",
  },
  { table: "auth_sessions", column: "user_id", referencedTable: "users", referencedColumn: "id" },
  { table: "auth_sessions", column: "active_organization_id", referencedTable: "organizations", referencedColumn: "id" },
  {
    table: "ai_recommendation_runs",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "ai_recommendation_runs",
    column: "actor_profile_id",
    referencedTable: "profiles",
    referencedColumn: "id",
  },
  { table: "customers", column: "organization_id", referencedTable: "organizations", referencedColumn: "id" },
  { table: "jobs", column: "customer_id", referencedTable: "customers", referencedColumn: "id" },
  { table: "jobs", column: "organization_id", referencedTable: "organizations", referencedColumn: "id" },
  { table: "quotes", column: "job_id", referencedTable: "jobs", referencedColumn: "id" },
  { table: "invoices", column: "job_id", referencedTable: "jobs", referencedColumn: "id" },
  { table: "invoice_payments", column: "invoice_id", referencedTable: "invoices", referencedColumn: "id" },
  { table: "portal_magic_links", column: "customer_id", referencedTable: "customers", referencedColumn: "id" },
  { table: "portal_sessions", column: "customer_id", referencedTable: "customers", referencedColumn: "id" },
  { table: "quote_line_items", column: "quote_id", referencedTable: "quotes", referencedColumn: "id" },
  { table: "invoice_line_items", column: "invoice_id", referencedTable: "invoices", referencedColumn: "id" },
  { table: "marketing_profiles", column: "organization_id", referencedTable: "organizations", referencedColumn: "id" },
  {
    table: "marketing_connected_channels",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "marketing_campaigns",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  { table: "marketing_campaigns", column: "created_by_user_id", referencedTable: "users", referencedColumn: "id" },
  { table: "marketing_campaigns", column: "updated_by_user_id", referencedTable: "users", referencedColumn: "id" },
  {
    table: "marketing_campaign_items",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "marketing_campaign_items",
    column: "campaign_id",
    referencedTable: "marketing_campaigns",
    referencedColumn: "id",
  },
  {
    table: "marketing_campaign_items",
    column: "draft_id",
    referencedTable: "marketing_content_drafts",
    referencedColumn: "id",
  },
  {
    table: "marketing_automation_rules",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  { table: "marketing_automation_rules", column: "created_by_user_id", referencedTable: "users", referencedColumn: "id" },
  { table: "marketing_automation_rules", column: "updated_by_user_id", referencedTable: "users", referencedColumn: "id" },
  {
    table: "marketing_automation_runs",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "marketing_automation_runs",
    column: "rule_id",
    referencedTable: "marketing_automation_rules",
    referencedColumn: "id",
  },
  {
    table: "marketing_automation_runs",
    column: "marketing_opportunity_id",
    referencedTable: "marketing_opportunities",
    referencedColumn: "id",
  },
  {
    table: "marketing_automation_runs",
    column: "marketing_content_draft_id",
    referencedTable: "marketing_content_drafts",
    referencedColumn: "id",
  },
  {
    table: "marketing_opportunities",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "marketing_opportunities",
    column: "converted_draft_id",
    referencedTable: "marketing_content_drafts",
    referencedColumn: "id",
  },
  {
    table: "marketing_opportunities",
    column: "dismissed_by_user_id",
    referencedTable: "users",
    referencedColumn: "id",
  },
  {
    table: "marketing_content_drafts",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  { table: "marketing_content_drafts", column: "created_by_user_id", referencedTable: "users", referencedColumn: "id" },
  { table: "marketing_content_drafts", column: "updated_by_user_id", referencedTable: "users", referencedColumn: "id" },
  {
    table: "marketing_content_variants",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "marketing_content_variants",
    column: "draft_id",
    referencedTable: "marketing_content_drafts",
    referencedColumn: "id",
  },
  {
    table: "marketing_oauth_states",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "marketing_publish_jobs",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "marketing_publish_jobs",
    column: "draft_id",
    referencedTable: "marketing_content_drafts",
    referencedColumn: "id",
  },
  { table: "marketing_publish_jobs", column: "created_by_user_id", referencedTable: "users", referencedColumn: "id" },
  {
    table: "marketing_publish_attempts",
    column: "organization_id",
    referencedTable: "organizations",
    referencedColumn: "id",
  },
  {
    table: "marketing_publish_attempts",
    column: "publish_job_id",
    referencedTable: "marketing_publish_jobs",
    referencedColumn: "id",
  },
  {
    table: "owned_phone_numbers",
    column: "voice_flow_id",
    referencedTable: "voice_flows",
    referencedColumn: "id",
  },
] as const;
